### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asmitbm**
Updated Readme.md and added Contributors.md

### CODE REVIEW

**Comment by siddharth2798** [comment]
Hey @Asmit2952 , Can you add a link to the contributors file in readme? Probably with a one line description

**Comment by ghost** [comment]
@Asmit2952 maybe we can have some ref in `readme.md` file

**Comment by asmitbm** [comment]
> @Asmit2952 maybe we can have some ref in `readme.md` file

Sure I'll do that

**Comment by asmitbm** [comment]
Done!!

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Closes #15

**Pull request merged**
